header:
  version: 11

distro: poky

defaults:
  repos:
    refspec: gatesgarth

repos:
  meta-lx2k:

  meta-openembedded:
    url: https://git.openembedded.org/meta-openembedded
    layers:
      meta-oe:
      meta-python:

  poky:
    url: https://git.yoctoproject.org/git/poky
    layers:
      meta:
      meta-poky:

  meta-arm:
    url: https://git.yoctoproject.org/git/meta-arm
    layers:
      meta-arm-toolchain:
      meta-arm:

env:
  BB_LOGCONFIG: ""

local_conf_header:
  base: |
    EXTRA_IMAGE_FEATURES_append = " debug-tweaks"
    INHERIT += "rm_work"

machine: unset

target:
  - core-image-minimal
